### ISSUE TITLE
How to use Export/Import existing Table in JavaFx

### ISSUE THREAD

**Issue by ezizrehimov** [GemBoxLtd/GemBox.Spreadsheet.Java.Examples#2]
Hello. i have exitsing tableview. But i did not  can export or import this table values in xls file. (using with FileChooser)

This is Table class:

```

package main;

public class MMSI_Table {
    String col1, col2;


    public MMSI_Table(String col1, String col2) {
        this.col1 = col1;
        this.col2 = col2;
    }

    public String getCol1() {
        return col1;
    }

    public void setCol1(String col1) {
        this.col1 = col1;
    }

    public String getCol2() {
        return col2;
    }

    public void setCol2(String col2) {
        this.col2 = col2;
    }
}
```

I get table values with api .
This is Controller:

```
public class MMSI_Controller implements Initializable {


    MMSI_RequestAPI mmsi_requestAPI = MMSI_RequestAPI.getInstance();


    @FXML
    private TableView<MMSI_Table> table;

    @FXML
    private TableColumn<MMSI_Table, String> col1, col2;




    @Override
    public void initialize(URL location, ResourceBundle resources) {
        MMSI_Table_Values data = new MMSI_Table_Values();

        // TableView

        col1.setCellValueFactory(new PropertyValueFactory<MMSI_Table, String>("col1"));
        col2.setCellValueFactory(new PropertyValueFactory<MMSI_Table, String>("col2"));


        try {
            table.setItems(mmsi_requestAPI.tableValue());
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
```

**Comment by ezizrehimov** [comment]
i know fixed problem with export, but still dont can do import file my existing table.

**Comment by mayoturis** [comment]
Hi, I am afraid I don't understand which part of your code is problematic. Can you please describe how are you using GemBox.Spreadsheet for Java to achieve your goal? From your code, I don't see where you are using GemBox.Spreadsheet for Java.

**Comment by ezizrehimov** [comment]
I have existing tableView and it's have 2 column

```
@FXML
    private TableColumn<MMSI_Table, String> col1, col2;
```
i how set excel columns only this 2 column? ( col1,col2)

**Comment by mayoturis** [comment]
Are you using GemBox.Spreadsheet for Java library? 

It seems that you are having an issue with JavaFX and not with our component. If that is the case, please consult [JavaFX documentation](https://docs.oracle.com/javase/8/javase-clienttechnologies.htm).

**Comment by ezizrehimov** [comment]
i used your library. but your library , you will create new columns. but i am have existing table, how i set existing columns?(col1,col2)

**Comment by gemboxsoftware-dev-team** [comment]
What do you mean by "you will create new columns"?
Can you send us a small project that reproduces your issue so that we can investigate it?

**Comment by ezizrehimov** [comment]
```
   private void fillTable(String[][] dataSource) {
        table.getColumns().clear();

        ObservableList<ObservableList<String>> data = FXCollections.observableArrayList();
        for (String[] row : dataSource)
            data.add(FXCollections.observableArrayList(row));
        table.setItems(data);

        for (int i = 0; i < dataSource[0].length; i++) {
            final int currentColumn = i;
            TableColumn<ObservableList<String>, String> column = new TableColumn<>(ExcelColumnCollection.columnIndexToName(currentColumn));
            column.setCellValueFactory(param -> new ReadOnlyObjectWrapper<>(param.getValue().get(currentColumn)));
            column.setEditable(true);
            column.setCellFactory(TextFieldTableCell.forTableColumn());
            column.setOnEditCommit(
                    (TableColumn.CellEditEvent<ObservableList<String>, String> t) -> {
                        t.getTableView().getItems().get(t.getTablePosition().getRow()).set(t.getTablePosition().getColumn(), t.getNewValue());
                    });
            table.getColumns().add(column);
        }
    }
```
You will crete here new columns : 
```
       TableColumn<ObservableList<String>, String> column = new TableColumn<>(ExcelColumnCollection.columnIndexToName(currentColumn));
```
But i am have existing columns.
```
@FXML
    private TableColumn<MMSI_Table, String> col1, col2;
```

how i set xls file values only this 2 columns?(col1,col2)

**Comment by gemboxsoftware-dev-team** [comment]
The following code writes the data to an `ExcelFile` object:
```java
ExcelFile file = new ExcelFile();
ExcelWorksheet worksheet = file.addWorksheet("sheet");
for (int row = 0; row < table.getItems().size(); row++) {
    ObservableList cells = (ObservableList) table.getItems().get(row);
    for (int column = 0; column < cells.size(); column++) {
        if (cells.get(column) != null)
            worksheet.getCell(row, column).setValue(cells.get(column).toString());
    }
}
```
What you'll need to do is change that writing per your requirement.
Now unfortunately, it's hard for me to suggest exactly what change you need to do because I still don't have a clear picture as to what you're doing and how you're using GemBox.Spreadsheet for Java.

If you can send us a small sample project I could help you out with it.
If not, please try referring to our [Writing](https://www.gemboxsoftware.com/spreadsheet-java/examples/create-write-excel-file-in-java/402) example.

I hope this helps.

Regards,
Mario

**Comment by ezizrehimov** [comment]
please use this : 

https://github.com/ezizrehimov/ExcelTest.git

i used Java 8 version . Jdk 8 or 1.8


I here have existing table and table's 2 column.
How i import xlsx or csv file this 2 column? and how i export this 2 column values in xlsx or csv file?

**Comment by gemboxsoftware-dev-team** [comment]
Apologize, but this project doesn't use GemBox.Spreadsheet for Java anywhere.
Have you tried using our library?
Have you tried checking out our reading and writing examples?

**Comment by ezizrehimov** [comment]
I added. please look again. 
```
java: incompatible types: javafx.collections.ObservableList<javafx.collections.ObservableList<java.lang.String>> cannot be converted to javafx.collections.ObservableList<sample.Table>
```

I now getting error 
Controller.java: 89 (line)
and 
Controll.java:101 ( line)

**Comment by gemboxsoftware-dev-team** [comment]
I'm afraid that question doesn't have anything to do with GemBox.Spreadsheet for Java.
Apologize for the inconvenience, but I'm afraid I can help you out only with inquiries that are specific to GemBox.Spreadsheet for Java library.

**Comment by gemboxsoftware-dev-team** [comment]
With that in mind, please note that if you don't have any specific questions regarding GemBox.Spreadsheet for Java, I'll need to close this GitHub Issue.

**Comment by ezizrehimov** [comment]
okay. thank you.
